id: 49e80f4b85604f8f84190ba8a49b1de8
title: Toh_340-The_Hundred_Deeds-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-073-001
  eft-text-version: 1.2.2 2020
